version: '3.8'

services:
  # Наш Центральный Асинхронный REST API Шлюз (FastAPI)
  app:
    build: .
    image: rellixcore/qspro:1.0.0
    container_name: qspro_app
    restart: always
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - db
      - redis

  # Промышленный Хранитель Базы Данных (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: qspro_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Сверхскоростной Кэш и Брокер Уведомлений (Redis)
  redis:
    image: redis:7-alpine
    container_name: qspro_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: